name: Security Report
description: Report a security concern
title: "[Security]: "
labels:
  - security

body:
  - type: markdown
    attributes:
      value: |
        Please DO NOT disclose vulnerabilities publicly.

  - type: textarea
    id: issue
    attributes:
      label: Security Issue
